version: '3.6'
services:
  iris:
    image: environnement-framework
    restart: always
    #command: --check-caps false
    ports: 
      - 51773
      - 52773:52773
      - 53773
    volumes:
      - databases-framework:/databases
      - ../../:/opt/iriscode/
volumes:
   databases-framework:
    external: true
